# Generated by Django 5.2.8 on 2026-01-05 17:33

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        CreateExtension('pg_trgm'),
    ]
